Algoritmo "Estrutura Repetitiva ENQUANTO"

// É uma ESTRUTURA DE CONTROLE que REPETE um bloco de comandos ENQUANTO uma CONDICÃO for verdadeira.

// USA-SE quando NÃO se sabe previamente a quantidade e repetições será realizada.


Var
// Sintaxe da Estrutura

Inicio

      enquanto condição faca               // Regra:
         comando 1
         comando 2                         // V: executa e volta
      fimenquanto                          // F: pula fora



Fimalgoritmo