Algoritmo "ESTRUTURA REPETITIVA 'REPITA-ATE'"
//  Menos utilizada. Mas em alguns casos encaixa melhor ao problema.

//  O bloco de comando EXECUPA PELO MENOS UMA VEZ, pois a CONDIÇÃO e verificado no FINAL.



Var

//  SINTAXE DA ESTRUTURA

Inicio

    repita                            //        REGRA:   OBS.: condiçao no final
       comando 1                      //    V: pula fora
       comando 2                      //    F: volta
    ate condicao



Fimalgoritmo