Algoritmo "Teste_Enquanto"
// Fazer um programa que lê números inteiros até que um zero seja lido.
// Ao final mostra a soma dos números lidos.


Var

   x, soma : inteiro


Inicio

   escreva("Digite o primeiro numero: ")
   leia(x)
   
   soma <- 0
   enquanto x <> 0 faca
      soma <- soma + x
      escreva("Digite outro numero: ")
      leia(x)
   fimenquanto

   escreval("SOMA: ", soma)
   
   

Fimalgoritmo